# Generated by Django 5.0.1 on 2024-01-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menuitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('details', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
