# Generated by Django 5.0.1 on 2024-01-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrokitchen_app', '0002_menuitem_menuimage_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='details',
            field=models.CharField(max_length=200, verbose_name='Item Details'),
        ),
    ]
