# Generated by Django 5.0.1 on 2024-01-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrokitchen_app', '0003_alter_menuitem_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.IntegerField(choices=[(1, 'Starter'), (2, 'Breakfast'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Bread & Rice')]),
        ),
    ]
