# Generated by Django 5.0.1 on 2024-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrokitchen_app', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('chefdetails', models.CharField(max_length=150)),
                ('chefimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
