# Generated by Django 5.0.1 on 2024-01-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrokitchen_app', '0008_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Chef's Name"),
        ),
    ]
