# Generated by Django 5.0.1 on 2024-01-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistrokitchen_app', '0011_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.CharField(max_length=150)),
                ('pname', models.CharField(max_length=50, verbose_name="Person's Name")),
                ('ptitle', models.CharField(max_length=50, verbose_name="Person's Title")),
                ('ptimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
